config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'teacher/index'
  get 'exam/index'
  get 'student/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
  def index
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
  end
end

app/controllers/student_controller.rb
class StudentsController < ApplicationController
  def index
    @student = Student.new
  end
  def create
    student = Student.new(resource_params)
        student.save
        flash[:notice] = 'Students has been created'
        redirect_to students_path
  end 
  def edit
    @book = Book.find(params[:id])
  end
def update
  @student = Student.find(params[:id])
        @student.update(resource_params)
        flash[:notice] = 'Student has been updated'
        redirect_to student_path(@student)
end
def destroy
  @student = Student.find(params[:id])
  @student.destroy
  flash[:notice] = 'Student has been deleted'
  redirect_to students_path
end
def index
  @students = Student.all
end
def show
  id = params[:id]
        @student = Student.find(id)
end
   private

def
  params.require(:student).permit(:nama, :username, :age, :kelas, :address, :city, :nik)
end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/exam/index.html.erb
<h1>Exam#index</h1>
<p>Find me in app/views/exam/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/report/index.html.erb
<h1>Report#index</h1>
<p>Find me in app/views/report/index.html.erb</p>

app/views/student/edit.html.erb
<%= form_for(@student) do |f| %>
    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.submit "Save" %>
<% end %>

app/views/student/index.html.erb
<% if flash[:notice].present? %>
   <%= flash[:notice] %>
<% end %> </br>
<table>
    <tr>
       <td>nama</td>
       <td>username</td>
       <td>age</td>
       <td>kelas</td>
       <td>address</td>
       <td>city</td>
       <td>nik</td>
    </tr>
    <% @students.each do |student| %>
        <tr>
        <td><%= student.nama %></td>
        <td><%= student.username %></td>
        <td><%= student.age %></td>
        <td><%= student.kelas %></td>
        <td><%= student.address %></td>
        <td><%= student.city %></td>
        <td><%= student.nik %></td>
        <td><%= link_to 'detail' , student_path(student) %> | <td><%= link_to 'Edit' , edit_student_path(student) %> | <td><%= link_to 'Delete' , student_path(student), method: :delete, data:{confirm: 'Are you sure?'} %> </td>
        </tr>
    <% end %>
</table>

<%= link_to 'New student' , new_student_path %>

# <h1>Student#index</h1>
# <p>Find me in app/views/student/index.html.erb</p>

app/views/student/new.html.erb
%= form_for(@student) do |f| %>
    <%= f.label :nama %> </br>
    <%= f.text_field :nama %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>

    <%= f.submit "Save" %>
<% end %>

app/views/student/show.html.erb
<% if flash[:notice].present? %>
   <%= flash[:notice] %>
<% end %> </br>
Nama : <%= @student.nama %> </br>
Username  : <%= @student.username  %> </br>
Age : <%= @student.age  %> </br>
Kelas : <%= @student.kelas  %> </br>
Address : <%= @student.address  %> </br>
City : <%= @student.city  %> </br>
Nik : <%= @student.nik  %> </br>

app/views/teacher/index.html.erb
<h1>Teacher#index</h1>
<p>Find me in app/views/teacher/index.html.erb</p>